name: Code Formatting

on:
    push:
        branches:
            - staging
    pull_request:
        branches:
            - main

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js and npm
              uses: actions/setup-node@v2
              with:
                  node-version: "21.1.0"

            - name: Install dependencies
              run: npm install

            - name: Format code with Prettier
              run: npm run format:write
